image: npetrovsky/docker-android-sdk-ndk

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - chmod +x ./gradlew # Here using private env variable also possible to pass signature to make signed APK 

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
    # - ./gradlew assembleRelease lintRelease signingReport --stacktrace
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_(${CI_COMMIT_TAG}:${CI_COMMIT_SHA})"
    paths:
      - app/build/outputs/
      - app/build/reports/
